
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obcmidpdmmiwokjcxlow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iY21pZHBkbW1pd29ramN4bG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzQyNTEsImV4cCI6MjA2NTcxMDI1MX0.7lLe71xkGSUhzkAWkThW3IA4PZgqgTKztugZ3wUKk8o";

// Create Supabase client with error handling for module loading issues
let supabase: ReturnType<typeof createClient<Database>>;

try {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
  // Fallback client that won't break the app
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      persistSession: false
    }
  });
}

export { supabase };
